---

- name: Include OS specific vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: set vars
  set_fact:
    "{{ var }}": "{{ lookup('vars', '__' + var) }}"
  when: not lookup('vars', var, default=false)
