---
- name: Include dynamic vars
  include_tasks: load_vars.yml
  with_items:
    - "monitoring_plugins_{{ ansible_distribution }}_all"
    - "monitoring_plugins_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"
    - "monitoring_plugins_custom_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"
    - "monitoring_plugins_path"
    - "monitoring_plugins_user"
  vars:
    var: "{{ main_item }}"
  loop_control:
    loop_var: main_item

- name: install plugins for os family
  include_tasks: "{{ ansible_os_family }}.yml"

- name: deploy eventhandlers if required
  include_tasks: eventhandlers.yml
  when: monitoring_plugins_eventhandlers|bool

- name: copy our own custom nagios checks
  copy:
    src: "{{ item }}"
    dest: "{{ __monitoring_plugins_path }}"
    owner: root
    group: root
    mode: 0755
  with_fileglob: "../files/custom_checks/*"

- name: get current SELinux status
  shell: sestatus | grep ^"SELinux status" | awk '{print $NF}'
  register: selinuxstatus

- name: build a list of our own custom nagios checks
  local_action: 
    module: shell 
    _raw_params: "customdir=$(find / -type d -wholename /*/monitoring_plugins/files/custom_checks) ; find $customdir -type f"
  register: customnagiosfiles
  when: selinuxstatus.stdout == "enabled"

- name: set SELinux contexts on custom nagios checks
  command: chcon -t nagios_unconfined_plugin_exec_t "{{ item | basename }}"
  args:
    chdir: "{{ __monitoring_plugins_path }}"
  with_items:
    - "{{ customnagiosfiles.stdout_lines }}"
  when: selinuxstatus.stdout == "enabled"

- name: copy check_mysql to check_mysqldb
  copy:
    remote_src: yes
    src: "{{ __monitoring_plugins_path }}/check_mysql"
    dest: "{{ __monitoring_plugins_path }}/check_mysqldb"
    owner: root
    group: root
    mode: 0755
