---
- name: Configure master server
  command: "icinga2 node setup --master --disable-confd --cn {{ icinga2_cn }}"
  args:
    creates: "/var/lib/icinga2/certs/{{ icinga2_cn }}.crt"
  notify: restart icinga2

- name: Create zones.d config dirs
  file:
    path: "/etc/icinga2/zones.d/{{ item }}"
    state: directory
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: "0755"
  with_items:
    - global-templates
    - global-templates/groups
    - master
    - satellite-hav # Satellite zone 1
    - satellite-fab # Satellite zone 2
    #- satellite.d

- name: Define zone configuration in zones.conf
  template:
    src: /etc/ansible/icinga2/config_files/master1_zones.conf.j2
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0644
    backup: yes
  notify: restart icinga2

#- name: Include satellite zone configuration in icinga2.conf
#  lineinfile:
#    path: /etc/icinga2/icinga2.conf
#    insertafter: EOF
#    line: 'include_recursive "satellite.d"'
#  notify: restart icinga2

#- name: Document satellite.d config dir
#  copy:
#    dest: /etc/icinga2/satellite.d/README
#    owner: "{{ icinga2_user }}"
#    group: "{{ icinga2_user }}"
#    content: |
#      This directory contains the Satellite zone definitions, not the Satellite client host.conf.
#      It's required since Icinga 2.11:
#      https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#config-sync-zones-in-zones

- name: Put base configuration templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icinga2/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - constants.conf
    - conf.d/api-users.conf
  notify: restart icinga2

- name: Include api-users.conf configuration in icinga2.conf
  lineinfile:
    path: /etc/icinga2/icinga2.conf
    insertafter: EOF
    line: 'include "conf.d/api-users.conf"'
  notify: restart icinga2

- name: Create features-available configuration files
  template:
    src: "features/{{ item }}.j2"
    dest: "/etc/icinga2/features-available/{{ item }}"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: "0640"
  with_items:
    - ido-mysql.conf
    - api.conf
  notify: restart icinga2

- name: Add global templates in /etc/icinga2/zones.d/global-templates/
  template:
    src: "{{ item }}"
    dest: /etc/icinga2/zones.d/global-templates/
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: "0644"
  with_fileglob:
    - ../templates/global-templates/*
  notify: restart icinga2
  tags:
    - templates

- name: Disable notifications where required
  command: icinga2 feature disable notification
  args:
    removes: /etc/icinga2/features-enabled/notification.conf
  when: not icinga2_notifications|bool
  notify: restart icinga2
  tags:
    - notifications

- name: Enable notifications where required
  command: icinga2 feature enable notification
  args:
    creates: /etc/icinga2/features-enabled/notification.conf
  when: icinga2_notifications|bool
  notify: restart icinga2
  tags:
    - notifications

- name: Create icinga2 database
  mysql_db:
    name: "{{ icinga2_idodb_name }}"
    state: present
  register: icingadb
  notify: create icinga2 db

- name: Create icinga2 database user
  mysql_user:
    name: "{{ icinga2_idodb_user }}"
    password: "{{ icinga2_idodb_pass }}"
    priv: "{{ icinga2_idodb_name }}.*:ALL"
    append_privs: true
    state: present

- name: Enable ido-mysql feature for icinga2web
  command: icinga2 feature enable ido-mysql
  #args:
  #  creates: /etc/icinga2/features-enabled/ido-mysql.conf
  notify: restart icinga2

- name: SElinux | allow master to connect to other hosts for curl webservice requests (notifications)
  seboolean:
    name: icinga2_can_connect_all
    state: true
    persistent: true
  when: ansible_selinux.status|default(false) == "Enabled"
