---
- name: configure master server
  command: "icinga2 node setup --master --disable-confd --cn {{ icinga2_cn }}"
  args:
    creates: "/var/lib/icinga2/certs/{{ icinga2_cn }}.crt"
  notify: restart icinga2

- name: create zones.d config dirs
  file:
    path: "/etc/icinga2/zones.d/{{ item }}"
    state: directory
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: "0755"
  with_items:
    - global-templates
    - global-templates/groups
    - master
    - satellite-hav # Satellite zone 1
    - satellite-fab # Satellite zone 2

- name: define zone configuration in zones.conf
  template:
    src: "{{ config_files }}/master1_zones.conf.j2"
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0644
  notify: restart icinga2

- name: create master .conf file in /etc/icinga2/zones.d/master
  template:
    src: "{{ config_files }}/master1.conf.j2"   
    dest: "/etc/icinga2/zones.d/master/{{ master1 }}.conf"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0644
  notify: restart icinga2

- name: put base configuration templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icinga2/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - constants.conf
    - conf.d/api-users.conf
  notify: restart icinga2

- name: include api-users.conf configuration in icinga2.conf
  lineinfile:
    path: /etc/icinga2/icinga2.conf
    insertafter: EOF
    line: 'include "conf.d/api-users.conf"'
  notify: restart icinga2

- name: create features-available configuration files
  template:
    src: "features/{{ item }}.j2"
    dest: "/etc/icinga2/features-available/{{ item }}"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: "0640"
  with_items:
    - ido-mysql.conf
    - api.conf
  notify: restart icinga2

- name: add global templates in /etc/icinga2/zones.d/global-templates/
  template:
    src: "{{ item }}"
    dest: /etc/icinga2/zones.d/global-templates/
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: "0644"
  with_fileglob:
    - ../templates/global-templates/*
  notify: restart icinga2
  tags:
    - templates

- name: disable notifications where required
  command: icinga2 feature disable notification
  args:
    removes: /etc/icinga2/features-enabled/notification.conf
  when: not icinga2_notifications|bool
  notify: restart icinga2
  tags:
    - notifications

- name: enable notifications where required
  command: icinga2 feature enable notification
  args:
    creates: /etc/icinga2/features-enabled/notification.conf
  when: icinga2_notifications|bool
  notify: restart icinga2
  tags:
    - notifications

- name: create icinga2 database
  mysql_db:
    name: "{{ icinga2_idodb_name }}"
    state: present
  register: icingadb
  delegate_to: "{{ groups.icinga2dbserver[0] }}" 

- name: slurp contents of database schema file
  slurp:
    src: /usr/share/icinga2-ido-mysql/schema/mysql.sql
  register: icinga2schema
  when: icingadb.changed

- name: create temporary database schema file
  copy:
    content: "{{ icinga2schema['content'] | b64decode }}"
    dest: /tmp/icingadb.sql
  when: icingadb.changed
  delegate_to: "{{ groups.icinga2dbserver[0] }}" 

- name: import icinga2 database schema
  mysql_db:
    state: import
    name: "{{ icinga2_idodb_name }}"
    target: /tmp/icingadb.sql
  when: icingadb.changed
  delegate_to: "{{ groups.icinga2dbserver[0] }}" 

- name: remove temporary database schema file
  file:
    path: /tmp/icingadb.sql
    state: absent
  delegate_to: "{{ groups.icinga2dbserver[0] }}"

- name: create icinga2 database users
  mysql_user:
    name: "{{ icinga2_idodb_user }}"
    password: "{{ icinga2_idodb_pass }}"
    priv: "{{ icinga2_idodb_name }}.*:ALL"
    host: "{{ item }}"
    append_privs: true
    state: present
  with_items: 
    - "{{ master1 }}"
    - "{{ master2 }}"
  delegate_to: "{{ groups.icinga2dbserver[0] }}" 

- name: enable ido-mysql feature for icinga2web
  command: icinga2 feature enable ido-mysql
  notify: restart icinga2

- name: SElinux | allow master to connect to other hosts for curl webservice requests (notifications)
  seboolean:
    name: icinga2_can_connect_all
    state: true
    persistent: true
  when: ansible_selinux.status|default(false) == "Enabled"
