---
#- name: check for service_facts
#  service_facts:
#  register: services
#  BUG ON UBUNTU

- name: ufw | open icinga ports
  ufw:
    rule: allow
    port: "{{ icinga2_network_port }}"
    proto: "{{ icinga2_network_proto }}"
  when: ansible_os_family == "Debian"

- name: firewalld | open icinga ports
  firewalld:
    port: "{{ icinga2_network_port }}/{{ icinga2_network_proto }}"
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == "RedHat"
    #and services.ansible_facts.services["firewalld.service"] is defined
    #and services.ansible_facts.services["firewalld.service"].state == "running"
