version: '2'

services:

  wordpress:
    image: arm32v7/wordpress:latest
    container_name: wordpress
    ports:
     - "80:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpressdb1
    restart: on-failure

  database: 
    image: hypriot/rpi-mysql:latest 
    container_name: mysql
    volumes:
    - /var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: wordpressdb1
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
