version: '2'
services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
     - /mnt/NAS:/mnt/NAS
    ports:
     - "80:80"
    restart: on-failure

  monitoring: 
    image: portainer/portainer:latest
    container_name: portainer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "9000:9000"
    restart: on-failure
