---
galaxy_info:
  author: Luc Stroobant
  description: Icinga2 checks role

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      version:
        - 10
    - name: Ubuntu
      version:
        - 18

  galaxy_tags:
    - fiaasco
    - icinga2
    - checks

dependencies: []
