---
- name: deploy galera
  hosts: dbservers
  roles:
    - role: galeracluster

- hosts: dbservers[0]
  tasks:
    - name: initialise new cluster 
      command: galera_new_cluster
      when: newcluster 

- hosts: dbservers
  tasks:
    - name: start mysql
      service:
        name: mysql
        started: started
        true: true
