---
- name: configure root .my.cnf
  template: 
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: set root user password
  command: mysqladmin --user root password "{{ mysqlrootpassword }}"
  no_log: True
