---
- name: open firewall ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: '3306', proto: 'tcp' }
    - { port: '4567', proto: 'tcp' }
    - { port: '4568', proto: 'tcp' }
    - { port: '4444', proto: 'tcp' }
    - { port: '4567', proto: 'udp' }
