---

# Don't impose a firewall choice, check for both firewalld
# or ufw service and enable or leave untouched as your infrastructure prefers it
# We assume
# - firewalld = RedHat and derivatives
# - ufw = Debian and derivatives

- name: check for service_facts
  service_facts:
  register: services

- name: ufw | open icingaweb ports
  ufw:
    rule: allow
    name: "{{ item }}"
  with_items:
    - Apache Full
    #- Apache Secure
  when: >
    services.ansible_facts.services.ufw is defined
    and services.ansible_facts.services.ufw.state == "running"

- name: firewalld | open icingaweb ports
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items: 
    - http
    - https
  when: >
    ansible_os_family == "RedHat"
    and services.ansible_facts.services["firewalld.service"] is defined
    and services.ansible_facts.services["firewalld.service"].state == "running"

# This task needs to be repeated because of
# https://wadman.co.nz/2018/11/17/Ansible-Firewalld-Module-On-Ubuntu/
#- name: firewalld | open icingaweb ports
#  firewalld:
#    service: "{{ item }}"
#    permanent: true
#    state: enabled
#    immediate: true
#  with_items:
#    - http
#    - https
#  when: >
#    ansible_os_family == "Debian"
#    and services.ansible_facts.services["firewalld.service"] is defined
#    and services.ansible_facts.services["firewalld.service"].state == "running"
#  vars:
#    ansible_python_interpreter: '/usr/bin/python3'
#
#- name: Reload firewalld
#  command: firewall-cmd reload
#  when: >
#    ansible_os_family == "RedHat"
#    and services.ansible_facts.services["firewalld.service"] is defined
#    and services.ansible_facts.services["firewalld.service"].state == "running"
