---
#- name: check for service_facts
#  service_facts:
#  register: services
#  BUG ON UBUNTU

- name: ufw | open icingaweb ports
  ufw:
    rule: allow
    name: "{{ item }}"
  with_items:
    - Apache Full
    #- Apache Secure
  when: ansible_os_family == "Debian"

- name: firewalld | open icingaweb ports
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items: 
    - http
    - https
  when: ansible_os_family == "RedHat"
    #and services.ansible_facts.services["firewalld.service"] is defined
    #and services.ansible_facts.services["firewalld.service"].state == "running"
