---
- name: add icinga repo key
  apt_key:
    url: https://packages.icinga.com/icinga.key
    state: present
  register: result
  retries: 3
  delay: 3
  until: result is not failed

- name: add icinga repo
  apt_repository:
    repo: "deb http://packages.icinga.com/{{ ansible_distribution|lower }} icinga-{{ ansible_distribution_release }} main"
    state: present

- name: install icingaweb2 and required packages
  apt:
    name:
      - icingaweb2
      - libapache2-mod-php
      - icinga2-ido-mysql
      - python-mysqldb
    state: present
  when: ansible_distribution_major_version <= "18"

- name: install icingaweb2 and required packages
  apt:
    name:
      - icingaweb2
      - libapache2-mod-php
      - icinga2-ido-mysql
      - python3-mysqldb
    state: present
  when: ansible_distribution_major_version >= "20"

- name: enable php module
  command: "phpenmod {{ item }}"
  args:
    creates: "/etc/php/{{ icinga2_icingaweb2_php_version }}/cli/conf.d/20-{{ item }}.ini"
  with_items:
    - imagick
    - intl
