---
- name: check site is defined for clients
  debug:
    msg: site is defined as {{ site }}
  failed_when: not site
  when: icinga_is_client|default(False) == True

- name: import zone and endpoint vars for fab clients
  include_vars:
    file: "fab.yml"
  when: icinga_is_client|default(False) == True and site == "fab"

- name: import zone and endpoint vars for hav clients
  include_vars:
    file: "hav.yml"
  when: icinga_is_client|default(False) == True and site == "hav"

- name: stop service when reprovisioning
  service:
    name: icinga2
    state: stopped
  ignore_errors: true
  when: icinga_client_reprovision

- name: remove files to force new certificate signing from master and remove existing api config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/icinga2/zones.conf.orig
    - /var/lib/icinga2/certs/ca.crt
    - /var/lib/icinga2/api
  when: icinga_client_reprovision

- name: put configuration templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icinga2/{{ item }}"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0640
  with_items:
    - icinga2.conf
  notify: restart icinga2

- name: allow to change a host zone when reprovisioning (otherwise configured by node setup)
  lineinfile:
    path: /etc/icinga2/constants.conf
    regexp: '^const ZoneName ='
    line: 'const ZoneName = {{ icinga_zone|default("NodeName") }}'
  when: icinga_client_reprovision
  notify: restart icinga2

- name: generate ticket
  command: icinga2 pki ticket --cn {{ inventory_hostname }} --salt {{ icinga2_ticketsalt }}
  args:
    creates: /etc/icinga2/zones.conf.orig
  register: ticket

- name: show ticket
  debug:
    var: ticket.stdout

- name: prepare pki directory
  file:
    path: /var/lib/icinga2/certs
    state: directory
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0755

- name: generate a new local self-signed certificate
  command: >
    icinga2 pki new-cert --cn {{ inventory_hostname }}
    --key /var/lib/icinga2/certs/{{ inventory_hostname }}.key
    --cert /var/lib/icinga2/certs/{{ inventory_hostname }}.crt
  args:
    creates: "/var/lib/icinga2/certs/{{ inventory_hostname }}.crt"
  notify: restart icinga2

- name: request the master certificate from the parent host and store it as ca.crt
  command: >
    icinga2 pki save-cert
    --key /var/lib/icinga2/certs/{{ inventory_hostname }}.key
    --cert /var/lib/icinga2/certs/{{ inventory_hostname }}.crt
    --trustedcert /var/lib/icinga2/certs/ca.crt --host {{ item }}
  args:
    creates: /var/lib/icinga2/certs/ca.crt
  with_items: "{{ icinga_parent.endpoints|first }}"
  notify: restart icinga2
  throttle: 1

- name: run icinga2 node setup for client
  # don't add host and port if host in dmz or master connects to client
  #{% for ep in icinga_parent.endpoints %}--endpoint {{ ep }}{% if inventory_hostname not in groups.dmz|default([]) %},{{ ep }},5665{% endif %} {% endfor %}
  command: >
    icinga2 node setup
    --ticket {{ ticket.stdout }}
    --cn {{ inventory_hostname }}
    {% for ep in icinga_parent.endpoints %}--endpoint {{ ep }} {% endfor %}
    --zone {{ icinga_zone|default(inventory_hostname) }}
    --parent_host {{ icinga_parent.endpoints[0] }}
    --parent_zone {{ icinga_parent.zone }}
    --trustedcert /var/lib/icinga2/certs/ca.crt
    --accept-config
    --accept-commands
  args:
    creates: /etc/icinga2/zones.conf.orig
  notify: restart icinga2
  when: icinga_is_client|default(False) == True or icinga_is_secondmaster|default(False) == True

- name: run icinga2 node setup for satellite
  # don't add host and port if host in dmz or master connects to client
  #{% for ep in icinga_parent.endpoints %}--endpoint {{ ep }}{% if inventory_hostname not in groups.dmz|default([]) %},{{ ep }},5665{% endif %} {% endfor %}
  command: >
    icinga2 node setup
    --ticket {{ ticket.stdout }}
    --cn {{ inventory_hostname }}
    {% for ep in icinga_parent.endpoints %}--endpoint {{ ep }} {% endfor %} 
    --zone {{ icinga_zone|default(inventory_hostname) }}
    --parent_host {{ icinga_parent.endpoints[0] }}
    --parent_zone {{ icinga_parent.zone }}
    --trustedcert /var/lib/icinga2/certs/ca.crt
    --accept-config
    --accept-commands
  args:
    creates: /etc/icinga2/zones.conf.orig
  notify: restart icinga2
  when: icinga_is_satellite|default(False) == True

- name: modify /etc/icinga2/zones.conf for satellite-hav server 1
  template:
    src: "{{ config_files}}/satellite-hav1.j2"
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0640
  notify: restart icinga2
  when: inventory_hostname == groups.icinga2satellitehav[0]

- name: modify /etc/icinga2/zones.conf for satellite-hav server 2
  template:
    src: "{{ config_files}}/satellite-hav2.j2"
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0640
  notify: restart icinga2
  when: inventory_hostname == groups.icinga2satellitehav[1]

- name: modify /etc/icinga2/zones.conf for satellite-fab server 1
  template:
    src: "{{ config_files}}/satellite-fab1.j2"
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0640
  notify: restart icinga2
  when: inventory_hostname == groups.icinga2satellitefab[0]

- name: modify /etc/icinga2/zones.conf for satellite-fab server 2
  template:
    src: "{{ config_files}}/satellite-fab2.j2"
    dest: /etc/icinga2/zones.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0640
  notify: restart icinga2
  when: inventory_hostname == groups.icinga2satellitefab[1]

- name: put features configuration templates (executed after node setup to avoid overwrites)
  template:
    src: "features/{{ item }}.j2"
    dest: "/etc/icinga2/features-available/{{ item }}"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    mode: 0640
  with_items:
    - api.conf
  notify: restart icinga2

- name: ensure service is running
  systemd:
    name: icinga2
    state: started
    enabled: true
