---
#- name: check for service_facts
#  service_facts:
#  register: services
#  BUG ON UBUNTU

- name: ufw | open icinga ports
  ufw:
    rule: allow
    port: "{{ icinga2_network_port }}"
    proto: "{{ icinga2_network_proto }}"
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  when: ansible_os_family == "Debian"

- name: firewalld | open icinga ports
  firewalld:
    port: "{{ icinga2_network_port }}/{{ icinga2_network_proto }}"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
    #and services.ansible_facts.services["firewalld.service"] is defined
    #and services.ansible_facts.services["firewalld.service"].state == "running"
