---
- name: ufw | open icinga ports
  ufw:
    rule: allow
    port: "{{ icinga2_network_port }}"
    proto: "{{ icinga2_network_proto }}"
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  when: ansible_os_family == "Debian"

- name: firewalld | open icinga ports
  firewalld:
    port: "{{ icinga2_network_port }}/{{ icinga2_network_proto }}"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

- name: iptables | open icinga ports
  command: iptables -I INPUT -p tcp --dport 5665 -j ACCEPT -m comment --comment "allow icinga2 client connections"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= "6"
  register: rheliptables

- name: iptables save
  command: service iptables save
  args:
    warn: false
  when: rheliptables.changed
