---
- hosts: icinga2secondmaster
  roles:
    - role: monitoring_plugins
    - role: icinga2_client
    - role: icinga2_hostconfig

  post_tasks:
  - name: shutdown icinga2 client
    service: 
      name: icinga2 
      state: stopped

  - name: reconfigure local /etc/icinga2/zones.conf
    template:
      src: "{{ config_files }}/master2_zones.conf.j2"
      dest: /etc/icinga2/zones.conf
      owner: "{{ icinga2_user }}" 
      group: "{{ icinga2_user }}"
      mode: 0644
      force: yes

  - name: ufw | open icinga ports
    ufw:
      rule: allow
      port: "{{ icinga2_network_port | default('5665') }}"
      proto: "{{ icinga2_network_proto | default('tcp') }}"
    when: ansible_os_family == "Debian"

  - name: firewalld | open icinga ports
    firewalld:
      port: "{{ icinga2_network_port | default('5665') }}/{{ icinga2_network_proto | default('tcp') }}"
      permanent: true
      state: enabled
      immediate: true
    when: ansible_os_family == "RedHat"

- hosts: icinga2master
  tasks:
  - name: copy new master2.conf to master
    template:
      src: "{{ config_files }}/master2.conf.j2"
      dest: /etc/icinga2/zones.d/master/{{ master2 }}.conf
      owner: "{{ icinga2_user }}"
      group: "{{ icinga2_user }}"
      mode: 0644
      backup: no
      force: yes

  - name: check icinga2 configuration
    command: icinga2 daemon -C

  - name: reload icinga2
    service: 
      name: icinga2 
      state: started

- hosts: icinga2secondmaster
  tasks:
  - name: install icinga2-ido-mysql
    package:
      name: icinga2-ido-mysql
      state: present   

  - name: configure /etc/icinga2/features-available/ido-mysql.conf
    template:
      src: "{{ config_files }}/ido-mysql.conf.j2"
      dest: /etc/icinga2/features-available/ido-mysql.conf
      owner: "{{ icinga2_user }}"
      group: "{{ icinga2_user }}"
      mode: 0640
      force: yes

  - name: enable ido-mysql feature
    command: icinga2 feature enable ido-mysql

  - name: enable other features
    command: icinga2 feature enable "{{ item }}"
    with_items:
      - api

  - name: Check icinga2 configuration
    command: icinga2 daemon -C

  - name: Start icinga2 client
    service: 
      name: icinga2 
      state: restarted
...
