---
- name: setup lamp stack for master
  hosts: icinga2master
  become: true
  gather_facts: true
  tasks:
    - name: install packages
      apt:
        update_cache: true
        cache_valid_time: 3600
        name:
          - apache2
          #- php-fpm
          - mysql-server
        state: present
      when: ansible_os_family == 'Debian'

    - name: start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
        daemon_reload: yes
      with_items:
        #- php7.4-fpm
        - apache2
        - mysql
      when: ansible_os_family == 'Debian'

  #roles:
  #  - role: fiaasco.mariadb
  #    tags:
  #      - mariadb
  #  - role: fiaasco.apache2
  #    tags:
  #      - apache2
  #    when: ansible_os_family == 'Debian'
  #  - role: fiaasco.php7
  #    tags:
  #      - php7
  #    when: ansible_os_family == 'Debian'

  #post_tasks:
  #  - when: >
  #      ansible_os_family == 'RedHat'
  #      and ansible_distribution_major_version is version('8', '>=')
  #    name: minimal php and httpd preparations for EL 8
  #    block:
  #      - name: install packages
  #        yum:
  #          name:
  #            - httpd
  #            - php-fpm
  #          state: present
  #      - name: start and enable services
  #        service:
  #          name: "{{ item }}"
  #          state: started
  #          enabled: true
  #        with_items:
  #          - php-fpm
  #          - httpd
