---
- name: put client template on master
  template:
    src: host.conf.j2
    dest: "/etc/icinga2/zones.d/{{ icinga_parent.zone }}/{{ inventory_hostname }}.conf"
    owner: nagios
    group: nagios
    mode: 0644
  delegate_to: "{{ groups.icinga2master[0] }}"
  notify: reload master icinga2
  when: icinga_is_client

- name: put satellite template on master
  template:
    src: host.conf.j2
    dest: "/etc/icinga2/zones.d/{{ icinga_zone }}/{{ inventory_hostname }}.conf"
    owner: nagios
    group: nagios
    mode: 0644
  delegate_to: "{{ groups.icinga2master[0] }}"
  notify: reload master icinga2
  when: icinga_is_satellite

- name: copy HostGroups config to icinga master
  template:
    src: "hostgroups.conf.j2"
    dest: "/etc/icinga2/zones.d/global-templates/hostgroups.conf"
    owner: nagios
    group: nagios
    mode: 0644
  delegate_to: "{{ groups.icinga2master[0] }}"
  run_once: true
  when: icinga2_hostconfig_ansible_groups
  notify: reload master icinga2
